-- MySQL Script generated by MySQL Workbench
-- Fri May 20 10:28:53 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema locations_films
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema locations_films
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `locations_films` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `locations_films` ;

-- -----------------------------------------------------
-- Table `locations_films`.`Appartiennent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locations_films`.`Appartiennent` (
  `catégories_films_idCatégories_Films` INT NOT NULL,
  PRIMARY KEY (`catégories_films_idCatégories_Films`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `locations_films`.`catégories_films`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locations_films`.`catégories_films` (
  `idCatégories_Films` INT NOT NULL,
  `Action_Films` VARCHAR(45) NOT NULL,
  `Comédie_Films` VARCHAR(45) NOT NULL,
  `Aventure_Films` VARCHAR(45) NOT NULL,
  `Drame_Films` VARCHAR(45) NOT NULL,
  `Horreur_Films` VARCHAR(45) NOT NULL,
  `Appartiennent_catégories_films_idCatégories_Films` INT NOT NULL,
  PRIMARY KEY (`idCatégories_Films`),
  INDEX `fk_catégories_films_Appartiennent1_idx` (`Appartiennent_catégories_films_idCatégories_Films` ASC) VISIBLE,
  CONSTRAINT `fk_catégories_films_Appartiennent1`
    FOREIGN KEY (`Appartiennent_catégories_films_idCatégories_Films`)
    REFERENCES `locations_films`.`Appartiennent` (`catégories_films_idCatégories_Films`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `locations_films`.`loues`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locations_films`.`loues` (
  `id_Films` INT NOT NULL,
  `id_Client` INT NOT NULL,
  `Date_Location` VARCHAR(45) NOT NULL,
  `Date_Retour` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Films`, `id_Client`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `locations_films`.`Effectues`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locations_films`.`Effectues` (
  `client_id_Client` INT NOT NULL,
  PRIMARY KEY (`client_id_Client`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `locations_films`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locations_films`.`client` (
  `id_Client` INT NOT NULL,
  `Nom_Client` VARCHAR(45) NOT NULL,
  `Prénom_Client` VARCHAR(60) NOT NULL,
  `Email_Client` VARCHAR(45) NOT NULL,
  `loues_id_Films` INT NOT NULL,
  `loues_id_Client` INT NOT NULL,
  `Effectues_client_id_Client` INT NOT NULL,
  PRIMARY KEY (`id_Client`),
  INDEX `fk_client_loues_idx` (`loues_id_Films` ASC, `loues_id_Client` ASC) VISIBLE,
  INDEX `fk_client_Effectues1_idx` (`Effectues_client_id_Client` ASC) VISIBLE,
  CONSTRAINT `fk_client_loues`
    FOREIGN KEY (`loues_id_Films` , `loues_id_Client`)
    REFERENCES `locations_films`.`loues` (`id_Films` , `id_Client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_client_Effectues1`
    FOREIGN KEY (`Effectues_client_id_Client`)
    REFERENCES `locations_films`.`Effectues` (`client_id_Client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `locations_films`.`films`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locations_films`.`films` (
  `id_Films` INT NOT NULL,
  `Titre_Films` VARCHAR(40) NOT NULL,
  `DateSortie_Films` VARCHAR(30) NOT NULL,
  `Durée_Films` VARCHAR(40) NOT NULL,
  `Réalisateur_Films` VARCHAR(60) NOT NULL,
  `loues_id_Films` INT NOT NULL,
  `loues_id_Client` INT NOT NULL,
  `Appartiennent_catégories_films_idCatégories_Films` INT NOT NULL,
  PRIMARY KEY (`id_Films`, `loues_id_Films`, `loues_id_Client`),
  INDEX `fk_films_loues1_idx` (`loues_id_Films` ASC, `loues_id_Client` ASC) VISIBLE,
  INDEX `fk_films_Appartiennent1_idx` (`Appartiennent_catégories_films_idCatégories_Films` ASC) VISIBLE,
  CONSTRAINT `fk_films_loues1`
    FOREIGN KEY (`loues_id_Films` , `loues_id_Client`)
    REFERENCES `locations_films`.`loues` (`id_Films` , `id_Client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_films_Appartiennent1`
    FOREIGN KEY (`Appartiennent_catégories_films_idCatégories_Films`)
    REFERENCES `locations_films`.`Appartiennent` (`catégories_films_idCatégories_Films`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `locations_films`.`payement_client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locations_films`.`payement_client` (
  `idPayement_Client` INT NOT NULL,
  `Date_Payement` VARCHAR(45) NOT NULL,
  `Description_Payement` VARCHAR(40) NOT NULL,
  `Montant_Payement` VARCHAR(45) NOT NULL,
  `Effectues_client_id_Client` INT NOT NULL,
  PRIMARY KEY (`idPayement_Client`),
  INDEX `fk_payement_client_Effectues1_idx` (`Effectues_client_id_Client` ASC) VISIBLE,
  CONSTRAINT `fk_payement_client_Effectues1`
    FOREIGN KEY (`Effectues_client_id_Client`)
    REFERENCES `locations_films`.`Effectues` (`client_id_Client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
